GET http://localhost:3100/users 

###
POST http://localhost:3100/users
Content-Type: application/json

{
    "username": "Raj Mohan",
    "password": "Raj123"
}

###
POST http://localhost:3100/login
Content-Type: application/json

{
    "username": "Raj Mohan",
    "password": "Raj123"
}
