# Base image
FROM alpine:latest

# Command line
CMD ["echo", "Hello Docker!!!"]

# To create container from this image: 'docker build -t first-docker-file .' from this directory
# To view the images: 'docker images'
# To run docker: 'docker run first-docker-file'